spring:
  application:
    name: simple

  datasource:
    url: jdbc:postgresql://localhost:5432/company_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # You can use 'none' if you want manual schema management
    defer-datasource-initialization: false
    show-sql: true

  sql:
    init:
      mode: always

  data:
    mongodb:
      uri: mongodb://localhost:27017/audit_logs_db