apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app-enhanced.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app-enhanced.labels" . | nindent 4 }}
    {{- include "web-app-enhanced.backend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-app-enhanced.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-app-enhanced.backend.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.backend.env.springDatasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-backend-secret
                  key: SPRING_DATA_MONGODB_URI
            - name: WEB_APP_FRONTEND_URL
              value: {{ .Values.backend.env.webAppFrontendUrl | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.backend.env.s3Bucket | quote }}
            - name: AWS_S3_REGION
              value: {{ .Values.backend.env.s3Region | quote }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 15
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
