apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app-enhanced.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
