apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app-enhanced.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app-enhanced.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "web-app-enhanced.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
